### ISSUE TITLE
Vagrant provisioning failure

### ISSUE THREAD

**Issue by mikelrob** [fastlane/ci#1090]
Hey, I'm very excited about this project and think the task you folks are undertaking is immense!

I've been tying to get the system up using vagrant but I'm having some trouble that I can't resolve. I hope you could spare a moment to look.

I followed the Using `fastlane.ci` with Vagrant steps on the README but the provision script fails during `npm install` - complaining it cannot read property match of undefined.

I've attached the end of the console log and the ERR log outputs below.
I'd be very grateful if you could let know know your thoughts on why it won't seem to work in this case.

```
...
    default: Bundle complete! 32 Gemfile dependencies, 152 gems now installed.
    default: Use `bundle info [gemname]` to see where a bundled gem is installed.
    default: Post-install message from overcommit:
    default: Install hooks by running `overcommit --install` in your Git repository
    default: npm
    default:  ERR! Cannot read property 'match' of undefined
    default: 
    default: npm ERR! A complete log of this run can be found in:
    default: npm ERR!     /Users/vagrant/.npm/_logs/2018-07-17T15_16_37_203Z-debug.log
    default: 
    default: > fastlane-web@0.0.0 build /fastlane-ci
    default: > ng build --deploy-url="/.dist" --prod
    default: sh: ng: command not found
    default: npm
    default:  
    default: ERR!
    default:  
    default: file
    default:  sh
    default: npm
    default:  
    default: ERR!
    default:  
    default: code
    default:  ELIFECYCLE
    default: npm
    default:  
    default: ERR!
    default:  
    default: errno
    default:  ENOENT
    default: npm
    default:  
    default: ERR!
    default:  
    default: syscall
    default:  spawn
    default: npm
    default:  
    default: ERR!
    default:  fastlane-web@0.0.0 build: `ng build --deploy-url="/.dist" --prod`
    default: npm
    default:  
    default: ERR!
    default:  spawn ENOENT
    default: npm
    default:  
    default: ERR!
    default:  
    default: npm
    default:  
    default: ERR!
    default:  Failed at the fastlane-web@0.0.0 build script.
    default: npm
    default:  
    default: ERR!
    default:  This is probably not a problem with npm. There is likely additional logging output above.
    default: npm
    default:  
    default: WARN
    default:  Local package.json exists, but node_modules missing, did you mean to install?
    default: npm
    default:  
    default: ERR!
    default:  A complete log of this run can be found in:
    default: npm
    default:  
    default: ERR!
    default:      /Users/vagrant/.npm/_logs/2018-07-17T15_16_37_971Z-debug.log
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

2018-07-17T15_16_37_203Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 verbose npm-session 299ebb7a70ab5892
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall fastlane-web@0.0.0
7 info lifecycle fastlane-web@0.0.0~preinstall: fastlane-web@0.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 15ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:rollbackFailedOptional Completed in 0ms
16 timing stage:runTopLevelLifecycles Completed in 345ms
17 silly saveTree fastlane-web@0.0.0
17 silly saveTree +-- @angular/animations@5.2.11
17 silly saveTree +-- @angular/cdk@5.2.5
17 silly saveTree +-- @angular/cli@1.7.4
17 silly saveTree | +-- @angular-devkit/build-optimizer@0.3.2
17 silly saveTree | | +-- typescript@2.6.2
17 silly saveTree | | `-- webpack-sources@1.1.0
17 silly saveTree | |   `-- source-map@0.6.1
17 silly saveTree | +-- @angular-devkit/core@0.3.2
17 silly saveTree | | +-- ajv@5.5.2
17 silly saveTree | | `-- chokidar@1.7.0
17 silly saveTree | |   +-- async-each@1.0.1
17 silly saveTree | |   `-- readdirp@2.1.0
17 silly saveTree | +-- @angular-devkit/schematics@0.3.2
17 silly saveTree | | `-- @ngtools/json-schema@1.1.0
17 silly saveTree | +-- @ngtools/json-schema@1.2.0
17 silly saveTree | +-- @ngtools/webpack@1.10.2
17 silly saveTree | | +-- enhanced-resolve@3.4.1
17 silly saveTree | | | `-- memory-fs@0.4.1
17 silly saveTree | | `-- magic-string@0.22.5
17 silly saveTree | |   `-- vlq@0.2.3
17 silly saveTree | +-- @schematics/angular@0.3.2
17 silly saveTree | +-- @schematics/package-update@0.3.2
17 silly saveTree | +-- ajv@6.5.2
17 silly saveTree | | +-- fast-deep-equal@2.0.1
17 silly saveTree | | `-- json-schema-traverse@0.4.1
17 silly saveTree | +-- copy-webpack-plugin@4.4.3
17 silly saveTree | | +-- cacache@10.0.4
17 silly saveTree | | | +-- glob@7.1.2
17 silly saveTree | | | | +-- inflight@1.0.6
17 silly saveTree | | | | | +-- once@1.4.0
17 silly saveTree | | | | | | `-- wrappy@1.0.2
17 silly saveTree | | | | | `-- wrappy@1.0.2
17 silly saveTree | | | | `-- once@1.4.0
17 silly saveTree | | | +-- lru-cache@4.1.3
17 silly saveTree | | | | `-- yallist@2.1.2
17 silly saveTree | | | +-- mississippi@2.0.0
17 silly saveTree | | | | +-- concat-stream@1.6.2
17 silly saveTree | | | | +-- duplexify@3.6.0
17 silly saveTree | | | | | `-- end-of-stream@1.4.1
17 silly saveTree | | | | +-- end-of-stream@1.4.1
17 silly saveTree | | | | +-- flush-write-stream@1.0.3
17 silly saveTree | | | | +-- from2@2.3.0
17 silly saveTree | | | | +-- parallel-transform@1.1.0
17 silly saveTree | | | | +-- pump@2.0.1
17 silly saveTree | | | | +-- pumpify@1.5.1
17 silly saveTree | | | | +-- stream-each@1.2.2
17 silly saveTree | | | | `-- through2@2.0.3
17 silly saveTree | | | |   `-- xtend@4.0.1
17 silly saveTree | | | +-- move-concurrently@1.0.1
17 silly saveTree | | | | +-- aproba@1.2.0
17 silly saveTree | | | | +-- copy-concurrently@1.0.5
17 silly saveTree | | | | | +-- fs-write-stream-atomic@1.0.10
17 silly saveTree | | | | | `-- rimraf@2.6.2
17 silly saveTree | | | | +-- fs-write-stream-atomic@1.0.10
17 silly saveTree | | | | `-- rimraf@2.6.2
17 silly saveTree | | | +-- rimraf@2.6.2
17 silly saveTree | | | `-- y18n@4.0.0
17 silly saveTree | | +-- globby@7.1.1
17 silly saveTree | | | `-- array-union@1.0.2
17 silly saveTree | | |   `-- array-uniq@1.0.3
17 silly saveTree | | `-- is-glob@4.0.0
17 silly saveTree | |   `-- is-extglob@2.1.1
17 silly saveTree | +-- extract-text-webpack-plugin@3.0.2
17 silly saveTree | | `-- schema-utils@0.3.0
17 silly saveTree | |   `-- ajv@5.5.2
17 silly saveTree | +-- glob@7.1.2
17 silly saveTree | +-- html-webpack-plugin@2.30.1
17 silly saveTree | | +-- loader-utils@0.2.17
17 silly saveTree | | `-- pretty-error@2.1.1
17 silly saveTree | |   `-- utila@0.4.0
17 silly saveTree | +-- less@2.7.3
17 silly saveTree | | `-- request@2.81.0
17 silly saveTree | |   +-- http-signature@1.1.1
17 silly saveTree | |   | +-- assert-plus@0.2.0
17 silly saveTree | |   | `-- jsprim@1.4.1
17 silly saveTree | |   |   +-- assert-plus@1.0.0
17 silly saveTree | |   |   `-- verror@1.10.0
17 silly saveTree | |   |     `-- assert-plus@1.0.0
17 silly saveTree | |   `-- uuid@3.3.2
17 silly saveTree | +-- memory-fs@0.4.1
17 silly saveTree | +-- node-sass@4.9.2
17 silly saveTree | | +-- async-foreach@0.1.3
17 silly saveTree | | +-- chalk@1.1.3
17 silly saveTree | | | +-- ansi-styles@2.2.1
17 silly saveTree | | | `-- supports-color@2.0.0
17 silly saveTree | | +-- cross-spawn@3.0.1
17 silly saveTree | | | `-- which@1.3.1
17 silly saveTree | | +-- gaze@1.1.3
17 silly saveTree | | | `-- globule@1.2.1
17 silly saveTree | | +-- meow@3.7.0
17 silly saveTree | | | +-- minimist@1.2.0
17 silly saveTree | | | +-- normalize-package-data@2.4.0
17 silly saveTree | | | | `-- validate-npm-package-license@3.0.3
17 silly saveTree | | | `-- read-pkg-up@1.0.1
17 silly saveTree | | |   +-- find-up@1.1.2
17 silly saveTree | | |   | `-- path-exists@2.1.0
17 silly saveTree | | |   `-- read-pkg@1.1.0
17 silly saveTree | | |     `-- path-type@1.1.0
17 silly saveTree | | |       `-- pify@2.3.0
17 silly saveTree | | +-- node-gyp@3.7.0
17 silly saveTree | | | +-- fstream@1.0.11
17 silly saveTree | | | +-- nopt@3.0.6
17 silly saveTree | | | | `-- abbrev@1.1.1
17 silly saveTree | | | +-- npmlog@4.1.2
17 silly saveTree | | | | +-- are-we-there-yet@1.1.5
17 silly saveTree | | | | `-- gauge@2.7.4
17 silly saveTree | | | |   `-- wide-align@1.1.3
17 silly saveTree | | | +-- semver@5.3.0
17 silly saveTree | | | `-- tar@2.2.1
17 silly saveTree | | +-- npmlog@4.1.2
17 silly saveTree | | +-- request@2.87.0
17 silly saveTree | | | +-- aws-sign2@0.7.0
17 silly saveTree | | | +-- form-data@2.3.2
17 silly saveTree | | | +-- har-validator@5.0.3
17 silly saveTree | | | | +-- ajv@5.5.2
17 silly saveTree | | | | `-- har-schema@2.0.0
17 silly saveTree | | | +-- http-signature@1.2.0
17 silly saveTree | | | | `-- assert-plus@1.0.0
17 silly saveTree | | | +-- performance-now@2.1.0
17 silly saveTree | | | `-- qs@6.5.2
17 silly saveTree | | +-- sass-graph@2.2.4
17 silly saveTree | | | `-- yargs@7.1.0
17 silly saveTree | | |   +-- camelcase@3.0.0
17 silly saveTree | | |   +-- cliui@3.2.0
17 silly saveTree | | |   | `-- wrap-ansi@2.1.0
17 silly saveTree | | |   +-- which-module@1.0.0
17 silly saveTree | | |   +-- y18n@3.2.1
17 silly saveTree | | |   `-- yargs-parser@5.0.0
17 silly saveTree | | +-- stdout-stream@1.4.0
17 silly saveTree | | `-- true-case-path@1.0.2
17 silly saveTree | |   `-- glob@6.0.4
17 silly saveTree | +-- postcss-url@7.3.2
17 silly saveTree | | `-- xxhashjs@0.2.2
17 silly saveTree | +-- stylus-loader@3.0.2
17 silly saveTree | | `-- when@3.6.4
17 silly saveTree | +-- stylus@0.54.5
17 silly saveTree | | +-- glob@7.0.6
17 silly saveTree | | `-- source-map@0.1.43
17 silly saveTree | |   `-- amdefine@1.0.1
17 silly saveTree | +-- uglifyjs-webpack-plugin@1.2.7
17 silly saveTree | | +-- schema-utils@0.4.5
17 silly saveTree | | | `-- ajv-keywords@3.2.0
17 silly saveTree | | +-- source-map@0.6.1
17 silly saveTree | | +-- uglify-es@3.3.9
17 silly saveTree | | | +-- commander@2.13.0
17 silly saveTree | | | `-- source-map@0.6.1
17 silly saveTree | | `-- worker-farm@1.6.0
17 silly saveTree | +-- webpack-dev-middleware@1.12.2
17 silly saveTree | +-- webpack-dev-server@2.11.2
17 silly saveTree | | +-- ansi-html@0.0.7
17 silly saveTree | | +-- chokidar@2.0.4
17 silly saveTree | | | +-- anymatch@2.0.0
17 silly saveTree | | | | `-- micromatch@3.1.10
17 silly saveTree | | | |   +-- arr-diff@4.0.0
17 silly saveTree | | | |   +-- array-unique@0.3.2
17 silly saveTree | | | |   +-- braces@2.3.2
17 silly saveTree | | | |   | +-- arr-flatten@1.1.0
17 silly saveTree | | | |   | +-- extend-shallow@2.0.1
17 silly saveTree | | | |   | +-- fill-range@4.0.0
17 silly saveTree | | | |   | | +-- extend-shallow@2.0.1
17 silly saveTree | | | |   | | `-- is-number@3.0.0
17 silly saveTree | | | |   | |   `-- kind-of@3.2.2
17 silly saveTree | | | |   | `-- isobject@3.0.1
17 silly saveTree | | | |   +-- extglob@2.0.4
17 silly saveTree | | | |   | +-- define-property@1.0.0
17 silly saveTree | | | |   | | `-- is-descriptor@1.0.2
17 silly saveTree | | | |   | |   +-- is-accessor-descriptor@1.0.0
17 silly saveTree | | | |   | |   | `-- kind-of@6.0.2
17 silly saveTree | | | |   | |   +-- is-data-descriptor@1.0.0
17 silly saveTree | | | |   | |   `-- kind-of@6.0.2
17 silly saveTree | | | |   | +-- expand-brackets@2.1.4
17 silly saveTree | | | |   | | +-- define-property@0.2.5
17 silly saveTree | | | |   | | | `-- is-descriptor@0.1.6
17 silly saveTree | | | |   | | |   +-- is-accessor-descriptor@0.1.6
17 silly saveTree | | | |   | | |   | `-- kind-of@3.2.2
17 silly saveTree | | | |   | | |   +-- is-data-descriptor@0.1.4
17 silly saveTree | | | |   | | |   | `-- kind-of@3.2.2
17 silly saveTree | | | |   | | |   `-- kind-of@5.1.0
17 silly saveTree | | | |   | | `-- extend-shallow@2.0.1
17 silly saveTree | | | |   | `-- extend-shallow@2.0.1
17 silly saveTree | | | |   `-- kind-of@6.0.2
17 silly saveTree | | | +-- braces@2.3.2
17 silly saveTree | | | +-- glob-parent@3.1.0
17 silly saveTree | | | | `-- is-glob@3.1.0
17 silly saveTree | | | `-- is-glob@4.0.0
17 silly saveTree | | +-- compression@1.7.3
17 silly saveTree | | | +-- accepts@1.3.5
17 silly saveTree | | | `-- vary@1.1.2
17 silly saveTree | | +-- debug@3.1.0
17 silly saveTree | | +-- del@3.0.0
17 silly saveTree | | | `-- globby@6.1.0
17 silly saveTree | | |   `-- pify@2.3.0
17 silly saveTree | | +-- express@4.16.3
17 silly saveTree | | | +-- array-flatten@1.1.1
17 silly saveTree | | | +-- qs@6.5.1
17 silly saveTree | | | +-- safe-buffer@5.1.1
17 silly saveTree | | | `-- utils-merge@1.0.1
17 silly saveTree | | +-- internal-ip@1.2.0
17 silly saveTree | | +-- sockjs-client@1.1.4
17 silly saveTree | | | `-- faye-websocket@0.11.1
17 silly saveTree | | |   `-- websocket-driver@0.7.0
17 silly saveTree | | |     `-- websocket-extensions@0.1.3
17 silly saveTree | | +-- sockjs@0.3.19
17 silly saveTree | | | `-- faye-websocket@0.10.0
17 silly saveTree | | +-- spdy@3.4.7
17 silly saveTree | | | `-- spdy-transport@2.1.0
17 silly saveTree | | |   +-- hpack.js@2.1.6
17 silly saveTree | | |   | `-- wbuf@1.7.3
17 silly saveTree | | |   `-- wbuf@1.7.3
17 silly saveTree | | +-- supports-color@5.4.0
17 silly saveTree | | | `-- has-flag@3.0.0
17 silly saveTree | | `-- yargs@6.6.0
17 silly saveTree | |   +-- y18n@3.2.1
17 silly saveTree | |   `-- yargs-parser@4.2.1
17 silly saveTree | +-- webpack-merge@4.1.3
17 silly saveTree | +-- webpack-sources@1.1.0
17 silly saveTree | +-- webpack-subresource-integrity@1.0.4
17 silly saveTree | | `-- webpack-core@0.6.9
17 silly saveTree | |   +-- source-list-map@0.1.8
17 silly saveTree | |   `-- source-map@0.4.4
17 silly saveTree | `-- webpack@3.11.0
17 silly saveTree |   +-- acorn-dynamic-import@2.0.2
17 silly saveTree |   | `-- acorn@4.0.13
17 silly saveTree |   +-- acorn@5.7.1
17 silly saveTree |   +-- node-libs-browser@2.1.0
17 silly saveTree |   | +-- assert@1.4.1
17 silly saveTree |   | | `-- util@0.10.3
17 silly saveTree |   | |   `-- inherits@2.0.1
17 silly saveTree |   | +-- punycode@1.4.1
17 silly saveTree |   | +-- stream-browserify@2.0.1
17 silly saveTree |   | +-- stream-http@2.8.3
17 silly saveTree |   | `-- vm-browserify@0.0.4
17 silly saveTree |   +-- supports-color@4.5.0
17 silly saveTree |   +-- uglifyjs-webpack-plugin@0.4.6
17 silly saveTree |   | `-- uglify-js@2.8.29
17 silly saveTree |   |   `-- yargs@3.10.0
17 silly saveTree |   |     +-- camelcase@1.2.1
17 silly saveTree |   |     +-- cliui@2.1.0
17 silly saveTree |   |     | `-- wordwrap@0.0.2
17 silly saveTree |   |     `-- window-size@0.1.0
17 silly saveTree |   +-- watchpack@1.6.0
17 silly saveTree |   | `-- chokidar@2.0.4
17 silly saveTree |   |   +-- anymatch@2.0.0
17 silly saveTree |   |   +-- glob-parent@3.1.0
17 silly saveTree |   |   | `-- is-glob@3.1.0
17 silly saveTree |   |   `-- is-glob@4.0.0
17 silly saveTree |   `-- yargs@8.0.2
17 silly saveTree |     +-- camelcase@4.1.0
17 silly saveTree |     +-- cliui@3.2.0
17 silly saveTree |     | `-- string-width@1.0.2
17 silly saveTree |     +-- os-locale@2.1.0
17 silly saveTree |     | `-- execa@0.7.0
17 silly saveTree |     |   `-- cross-spawn@5.1.0
17 silly saveTree |     +-- read-pkg-up@2.0.0
17 silly saveTree |     | +-- find-up@2.1.0
17 silly saveTree |     | `-- read-pkg@2.0.0
17 silly saveTree |     |   +-- load-json-file@2.0.0
17 silly saveTree |     |   | +-- pify@2.3.0
17 silly saveTree |     |   | `-- strip-bom@3.0.0
17 silly saveTree |     |   `-- path-type@2.0.0
17 silly saveTree |     +-- string-width@2.1.1
17 silly saveTree |     | +-- is-fullwidth-code-point@2.0.0
17 silly saveTree |     | `-- strip-ansi@4.0.0
17 silly saveTree |     |   `-- ansi-regex@3.0.0
17 silly saveTree |     +-- which-module@2.0.0
17 silly saveTree |     +-- y18n@3.2.1
17 silly saveTree |     `-- yargs-parser@7.0.0
17 silly saveTree |       `-- camelcase@4.1.0
17 silly saveTree +-- @angular/common@5.2.11
17 silly saveTree +-- @angular/compiler-cli@5.2.11
17 silly saveTree | +-- chokidar@1.7.0
17 silly saveTree | | +-- async-each@1.0.1
17 silly saveTree | | `-- readdirp@2.1.0
17 silly saveTree | `-- minimist@1.2.0
17 silly saveTree +-- @angular/compiler@5.2.11
17 silly saveTree +-- @angular/core@5.2.11
17 silly saveTree +-- @angular/forms@5.2.11
17 silly saveTree +-- @angular/http@5.2.11
17 silly saveTree +-- @angular/language-service@5.2.11
17 silly saveTree +-- @angular/material@5.2.5
17 silly saveTree +-- @angular/platform-browser-dynamic@5.2.11
17 silly saveTree +-- @angular/platform-browser@5.2.11
17 silly saveTree +-- @angular/router@5.2.11
17 silly saveTree +-- @types/jasmine@2.8.8
17 silly saveTree +-- @types/jasminewd2@2.0.3
17 silly saveTree +-- @types/moment@2.13.0
17 silly saveTree `-- @types/node@6.0.114
18 verbose stack TypeError: Cannot read property 'match' of undefined
18 verbose stack     at tarballToVersion (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
18 verbose stack     at inflatableChild (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
18 verbose stack     at BB.each (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
18 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Object.gotValue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
18 verbose stack     at Object.gotAccum (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
18 verbose stack     at Object.tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
18 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
18 verbose stack     at Promise._settlePromiseCtx (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
18 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
18 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
18 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
18 verbose stack     at runCallback (timers.js:696:18)
18 verbose stack     at tryOnImmediate (timers.js:667:5)
18 verbose stack     at processImmediate (timers.js:649:5)
19 verbose cwd /fastlane-ci
20 verbose Darwin 17.4.0
21 verbose argv "/usr/local/Cellar/node/10.6.0/bin/node" "/usr/local/bin/npm" "install"
22 verbose node v10.6.0
23 verbose npm  v6.1.0
24 error Cannot read property 'match' of undefined
25 verbose exit [ 1, true ]
```

2018-07-17T15_16_37_971Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle fastlane-web@0.0.0~prebuild: fastlane-web@0.0.0
6 info lifecycle fastlane-web@0.0.0~build: fastlane-web@0.0.0
7 verbose lifecycle fastlane-web@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle fastlane-web@0.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/fastlane-ci/node_modules/.bin:/Users/vagrant/.gem/ruby/2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle fastlane-web@0.0.0~build: CWD: /fastlane-ci
10 silly lifecycle fastlane-web@0.0.0~build: Args: [ '-c', 'ng build --deploy-url="/.dist" --prod' ]
11 info lifecycle fastlane-web@0.0.0~build: Failed to exec build script
12 verbose stack Error: fastlane-web@0.0.0 build: `ng build --deploy-url="/.dist" --prod`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:961:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
13 verbose pkgid fastlane-web@0.0.0
14 verbose cwd /fastlane-ci
15 verbose Darwin 17.4.0
16 verbose argv "/usr/local/Cellar/node/10.6.0/bin/node" "/usr/local/bin/npm" "run" "build"
17 verbose node v10.6.0
18 verbose npm  v6.1.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error fastlane-web@0.0.0 build: `ng build --deploy-url="/.dist" --prod`
23 error spawn ENOENT
24 error Failed at the fastlane-web@0.0.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```
